### ISSUE TITLE
Identify Apple II emulator

### ISSUE THREAD

**Issue by mswendyh** [retroTECHOnlineTeam/retroTechOnline#103]

**Comment by mmgerke** [comment]
I've identified a free open-source Apple IIe emulator, [linapple](https://github.com/linappleii/linapple) that has SDL support and can be started in full screen with the disk loaded from the command line.

(Klaus's requirements: SDL-based and ability to run via command line)

**Comment by mmgerke** [comment]
The emulator works well on Linux, but I'm getting a read-only error when inserting the cracked Ribbit disk images. The permissions are set correctly on the file so it requires more investigation...
