### ISSUE TITLE
Figure out how to pull data from ASpace API and display it on a page

### ISSUE THREAD

**Issue by mswendyh** [retroTECHOnlineTeam/retroTechOnline#149]
After some meeting with Heather and Chris, we've decided to try to display the data for each artifact on a separate page, which will be programmatically created on demand by utilizing a external PHP server run using Laravel and the ArchivesSpace API.

**Comment by mmgerke** [comment]
A note: must be connected to GT department VPN to get to ArchivesSpace staging
